<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <VersionPrefix>0.0.2</VersionPrefix>
    <VersionSuffix>
    </VersionSuffix>
    <Title>Backlot.Core</Title>
    <Authors>Jeroen Wijdeven Holding B.V.</Authors>
    <Copyright>(c) copyright Jeroen Wijdeven Holding B.V. 2026</Copyright>
    <PackageProjectUrl>https://www.backlot.software</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
    <PackageIcon>bl.png</PackageIcon>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Configurations>Debug;Release;Development</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <VersionSuffix>alpha-$([System.DateTime]::UtcNow.ToString(yyyyMMdd-HHmm))</VersionSuffix>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Development'">
    <VersionSuffix>beta</VersionSuffix>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\bl.png">
      <Pack>True</Pack>
      <PackagePath>
      </PackagePath>
      <Link>bl.png</Link>
    </None>
  </ItemGroup>
</Project>
