using System.ComponentModel.DataAnnotations;
using System.Text;
using Backlot.Core;
using Backlot.Core.Abstraction.Roles;
using Backlot.Core.Json;
using Backlot.Defaults.Scenarios.Configuration.Models;
using Newtonsoft.Json.Linq;
using FieldInfo = Backlot.Core.Abstraction.Roles.FieldInfo;

namespace Backlot.Defaults.Scenarios.Configuration;

/// <summary>
/// Renders the loaded scenarios and roles as TypeSpec (<c>.tsp</c>) source.
/// </summary>
/// <remarks>
/// TypeSpec is emitted rather than OpenAPI because it maps onto Backlot's model directly: the
/// response envelope is a single generic declaration instead of a per-operation repetition, the
/// "one role flat, multiple roles nested" request rule is a native construct, and models are
/// referenced by name -- so a self-referencing role keeps its shape instead of being truncated to
/// an empty object the way the example builder in <see cref="ScenarioSchemas"/> has to do it.
///
/// The consumer owns the toolchain from here: <c>tsp compile --emit @typespec/openapi3</c>, or any
/// client emitter. Backlot ships text and takes no dependency of its own. Verified against
/// TypeSpec 1.15.
/// </remarks>
internal static class TypeSpecEmitter
{
    private const string Indent = "  ";
    private const string EnvelopeName = "Envelope";

    /// <summary>
    /// Fields the role browser also hides: they are transport/metadata rather than role data.
    /// <see cref="Meta.__Skills"/> is added back explicitly for roles, mirroring the example builder.
    /// </summary>
    private static readonly string[] HiddenFields = [Meta.__Permission, Meta.__Skills, Meta.__Construct];

    public static string Emit(IReadOnlyCollection<ScenarioResultItem> scenarios, string directorRole)
    {
        var declarations = new Declarations();

        foreach (var scenario in scenarios)
        {
            // Only scenarios that carry a body contribute request models. A director scenario's
            // role is the director itself, whose properties are injected services rather than
            // contract data, and declaring it would leak IFileSystem and friends into the API.
            if (!IsGet(scenario, directorRole))
                foreach (var roleType in RequestRoles(scenario))
                    declarations.Require(roleType);

            declarations.Require(scenario.ResultType);
        }

        declarations.Drain();

        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Backlot from the scenarios loaded in this deployment.");
        sb.AppendLine("// Compile with: tsp compile <file> --emit @typespec/openapi3");
        sb.AppendLine();
        sb.AppendLine("import \"@typespec/http\";");
        sb.AppendLine();
        sb.AppendLine("using Http;");
        sb.AppendLine();
        sb.AppendLine("@service(#{ title: \"Backlot API\" })");
        sb.AppendLine("@useAuth(BasicAuth)");
        sb.AppendLine("namespace Backlot;");
        sb.AppendLine();

        sb.AppendLine("/** The response envelope every Backlot scenario returns. */");
        sb.AppendLine($"model {EnvelopeName}<T> {{");
        sb.AppendLine($"{Indent}Body: T;");
        sb.AppendLine($"{Indent}TimeInMs: int64;");
        sb.AppendLine($"{Indent}ExecutionTime: utcDateTime;");
        sb.AppendLine($"{Indent}Status: string;");
        sb.AppendLine("}");
        sb.AppendLine();

        declarations.Write(sb);
        WriteOperations(sb, scenarios, declarations, directorRole);

        return sb.ToString();
    }

    /// <summary>
    /// A scenario is played with GET only when the director itself is one of its roles. The
    /// endpoint path cannot be used for this: a multi-role scenario is also reachable through
    /// /api/role/director/... but still takes a body.
    /// </summary>
    private static bool IsGet(ScenarioResultItem scenario, string directorRole) =>
        (scenario.Roles ?? []).Contains(directorRole);

    /// <summary>
    /// The role types a scenario takes as request input, in the order <see cref="Scenarios"/>
    /// reported them.
    /// </summary>
    private static IEnumerable<Type> RequestRoles(ScenarioResultItem scenario) =>
        (scenario.Roles ?? [])
        .Select(name => Loader.TryGetRoleByName(name, out var type) ? type : null)
        .Where(type => type != null)!;

    private static void WriteOperations(StringBuilder sb, IEnumerable<ScenarioResultItem> scenarios,
        Declarations declarations, string directorRole)
    {
        // One interface per role segment of the endpoint, so the generated client groups the same
        // way the Studio's scenario list does.
        var operations = new SortedDictionary<string, SortedDictionary<string, string>>(StringComparer.Ordinal);

        foreach (var scenario in scenarios)
        {
            var isGet = IsGet(scenario, directorRole);
            var body = isGet ? null : RequestBody(scenario, declarations);
            var result = declarations.Reference(scenario.ResultType);

            foreach (var endpoint in scenario.Endpoints ?? [])
            {
                if (string.IsNullOrWhiteSpace(endpoint)) continue;

                var group = $"{Identifier(GroupName(RoleSegment(endpoint)), fallback: "Api")}Ops";
                if (!operations.TryGetValue(group, out var ops))
                    operations[group] = ops = new SortedDictionary<string, string>(StringComparer.Ordinal);

                var name = Unique(Identifier(scenario.Scenario, fallback: "op"), ops.ContainsKey);

                var op = new StringBuilder();
                op.AppendLine($"{Indent}@route(\"{endpoint}\")");
                op.AppendLine($"{Indent}{(isGet ? "@get" : "@post")}");
                op.AppendLine($"{Indent}{name}({body}): {EnvelopeName}<{result}>;");

                ops[name] = op.ToString();
            }
        }

        foreach (var (group, ops) in operations)
        {
            sb.AppendLine($"interface {group} {{");
            sb.AppendJoin(Environment.NewLine, ops.Values);
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// A single role posts its fields flat; multiple roles are each nested under their role name --
    /// the same rule <c>GetRoles.ForPostRequest</c> reads a request body with.
    /// </summary>
    private static string RequestBody(ScenarioResultItem scenario, Declarations declarations)
    {
        var roles = RequestRoles(scenario).ToArray();

        if (roles.Length == 0) return string.Empty;

        if (roles.Length == 1) return $"@body body: {declarations.Reference(roles[0])}";

        var parts = roles.Select(role => $"{Identifier(role.GetRoleName(), fallback: "role")}: {declarations.Reference(role)}");
        return $"@body body: {{ {string.Join("; ", parts)} }}";
    }

    /// <summary>
    /// The role part of "/api/role/{role}/{scenario}".
    /// </summary>
    private static string RoleSegment(string endpoint)
    {
        var segments = endpoint.Split('/', StringSplitOptions.RemoveEmptyEntries);
        return segments.Length >= 3 ? segments[2] : string.Empty;
    }

    /// <summary>
    /// Holds every named declaration the document needs, discovered breadth-first from the
    /// scenarios. A type is declared once and referenced by name afterwards, which is what lets
    /// recursive role graphs terminate without truncating them.
    /// </summary>
    private sealed class Declarations
    {
        private readonly Dictionary<Type, string> _names = new();
        private readonly Dictionary<Type, List<FieldInfo>> _models = new();
        private readonly HashSet<Type> _enums = [];
        private readonly Queue<Type> _pending = new();
        private readonly HashSet<string> _taken = new(StringComparer.Ordinal);

        /// <summary>
        /// Ensures <paramref name="type"/> (or the element type it wraps) has a declaration.
        /// Scalars need none.
        /// </summary>
        public void Require(Type? type)
        {
            type = Unwrap(type);
            if (type == null || Scalar(type) != null) return;

            var element = ElementType(type);
            if (element != null)
            {
                Require(element);
                return;
            }

            if (_names.ContainsKey(type)) return;

            _names[type] = Unique(Identifier(type.FriendlyName(), fallback: "Model"), _taken.Contains);
            _taken.Add(_names[type]);

            if (type.IsEnum) _enums.Add(type);
            else _pending.Enqueue(type);
        }

        /// <summary>
        /// Walks the queue until no newly referenced type is left undeclared.
        /// </summary>
        public void Drain()
        {
            while (_pending.Count > 0)
            {
                var type = _pending.Dequeue();
                var fields = Fields(type).ToList();
                _models[type] = fields;

                foreach (var field in fields)
                    Require(field.FieldType);
            }
        }

        /// <summary>
        /// The TypeSpec type expression for <paramref name="type"/>.
        /// </summary>
        public string Reference(Type? type)
        {
            type = Unwrap(type);
            if (type == null) return "Record<unknown>";

            var scalar = Scalar(type);
            if (scalar != null) return scalar;

            var element = ElementType(type);
            if (element != null) return $"{Reference(element)}[]";

            return _names.TryGetValue(type, out var name) ? name : "Record<unknown>";
        }

        public void Write(StringBuilder sb)
        {
            foreach (var type in _enums.OrderBy(t => _names[t], StringComparer.Ordinal))
            {
                sb.AppendLine($"enum {_names[type]} {{");
                foreach (var member in Enum.GetNames(type))
                    sb.AppendLine($"{Indent}{Identifier(member, fallback: "Value")},");
                sb.AppendLine("}");
                sb.AppendLine();
            }

            foreach (var type in _models.Keys.OrderBy(t => _names[t], StringComparer.Ordinal))
            {
                sb.AppendLine($"model {_names[type]} {{");

                foreach (var field in _models[type])
                    WriteField(sb, field);

                // Roles carry the list of role types the entity can also be presented as.
                if (typeof(IRole).IsAssignableFrom(type))
                    sb.AppendLine($"{Indent}{Quote(Meta.__Skills)}: string[];");

                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        private void WriteField(StringBuilder sb, FieldInfo field)
        {
            var decorators = new List<string>();

            if (Unwrap(field.FieldType) == typeof(Guid)) decorators.Add("@format(\"uuid\")");

            // Calculated fields are never persisted, so they are response-only.
            if (field.Attributes.Any(a => a is CalculatedAttribute)) decorators.Add("@visibility(Lifecycle.Read)");

            var prefix = decorators.Count > 0 ? string.Join(" ", decorators) + " " : string.Empty;
            var optional = Required(field) ? string.Empty : "?";

            sb.AppendLine($"{Indent}{prefix}{Quote(field.Name)}{optional}: {Reference(field.FieldType)};");
        }

        /// <summary>
        /// Required when explicitly validated as such, or when the CLR cannot omit it: a
        /// non-nullable value type is always serialized. Everything else is optional, which is what
        /// gives a generated client <c>field?: string</c> instead of marking the world mandatory.
        /// </summary>
        private static bool Required(FieldInfo field) =>
            field.Attributes.Any(a => a is RequiredAttribute) ||
            (field.FieldType.IsValueType && Nullable.GetUnderlyingType(field.FieldType) == null);

        private static IEnumerable<FieldInfo> Fields(Type type) =>
            type.GetFieldInfo()
                .Where(f => !f.Attributes.Any(a =>
                    a is Newtonsoft.Json.JsonIgnoreAttribute or System.Text.Json.Serialization.JsonIgnoreAttribute))
                .Where(f => !HiddenFields.Contains(f.Name, StringComparer.InvariantCultureIgnoreCase));
    }

    private static Type? Unwrap(Type? type) => type == null ? null : Nullable.GetUnderlyingType(type) ?? type;

    /// <summary>
    /// The TypeSpec scalar for a type Backlot serializes as a primitive, or null when the type
    /// needs a declaration of its own.
    /// </summary>
    private static string? Scalar(Type type)
    {
        if (type == typeof(string)) return "string";
        if (type == typeof(bool)) return "boolean";
        if (type == typeof(sbyte)) return "int8";
        if (type == typeof(short)) return "int16";
        if (type == typeof(int)) return "int32";
        if (type == typeof(long)) return "int64";
        if (type == typeof(byte)) return "uint8";
        if (type == typeof(ushort)) return "uint16";
        if (type == typeof(uint)) return "uint32";
        if (type == typeof(ulong)) return "uint64";
        if (type == typeof(decimal)) return "decimal128";
        if (type == typeof(double)) return "float64";
        if (type == typeof(float)) return "float32";
        if (type == typeof(Guid)) return "string";
        if (type == typeof(DateTime)) return "utcDateTime";
        if (type == typeof(DateTimeOffset)) return "offsetDateTime";
        if (type == typeof(TimeSpan)) return "duration";
        if (type == typeof(RoleReference)) return "string";
        if (type == typeof(JObject) || type == typeof(object)) return "Record<unknown>";
        if (type.IsEmptyOrAnonymous()) return "Record<unknown>";

        return null;
    }

    /// <summary>
    /// The element type when <paramref name="type"/> is a collection, otherwise null. Mirrors the
    /// unwrapping the example builder does.
    /// </summary>
    private static Type? ElementType(Type type)
    {
        if (type == typeof(string)) return null;
        if (type.IsArray) return type.GetElementType();

        if (type.IsGenericType)
        {
            var definition = type.GetGenericTypeDefinition();
            if (definition == typeof(IEnumerable<>) ||
                definition == typeof(ICollection<>) ||
                definition == typeof(IList<>) ||
                definition == typeof(List<>))
                return type.GetGenericArguments()[0];
        }

        return type
            .GetInterfaces()
            .FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>))
            ?.GetGenericArguments()[0];
    }

    /// <summary>
    /// A TypeSpec identifier built from a Backlot name. Generic friendly-names such as
    /// "List&lt;Person&gt;" lose their punctuation rather than their meaning.
    /// </summary>
    private static string Identifier(string name, string fallback)
    {
        if (string.IsNullOrWhiteSpace(name)) return fallback;

        var sb = new StringBuilder(name.Length);
        foreach (var c in name.Where(c => char.IsLetterOrDigit(c) || c == '_'))
            sb.Append(c);

        if (sb.Length == 0) return fallback;
        if (char.IsDigit(sb[0])) sb.Insert(0, '_');

        return sb.ToString();
    }

    /// <summary>
    /// <see cref="Scenarios"/> lowercases its endpoints, so "simplequery" has to be resolved back
    /// to the role it names before it becomes an interface a generated client calls through.
    /// Falls back to a leading capital for a segment no role answers to.
    /// </summary>
    private static string GroupName(string segment)
    {
        if (string.IsNullOrEmpty(segment)) return segment;

        return Loader.TryGetRoleByName(segment, out var role)
            ? role.GetRoleName()
            : char.ToUpperInvariant(segment[0]) + segment[1..];
    }

    private static string Unique(string name, Func<string, bool> taken)
    {
        if (!taken(name)) return name;

        for (var i = 2; ; i++)
        {
            var candidate = $"{name}{i}";
            if (!taken(candidate)) return candidate;
        }
    }

    /// <summary>
    /// Property names are emitted bare when they are valid identifiers and quoted otherwise, so a
    /// field name Backlot allows but TypeSpec would reject still round-trips.
    /// </summary>
    private static string Quote(string name)
    {
        var safe = name.Length > 0 &&
                   (char.IsLetter(name[0]) || name[0] == '_') &&
                   name.All(c => char.IsLetterOrDigit(c) || c == '_');

        return safe ? name : $"\"{name}\"";
    }
}
