<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VersionPrefix>0.0.1</VersionPrefix>
    <VersionSuffix>
    </VersionSuffix>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Backlot.DependencyInjection.Autofac</Title>
    <Authors>Jeroen Wijdeven Holding B.V.</Authors>
    <Copyright>(c) copyright Jeroen Wijdeven Holding B.V. 2026</Copyright>
    <PackageIcon>bl.png</PackageIcon>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Configurations>Debug;Release;Development</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <VersionSuffix>alpha-$([System.DateTime]::UtcNow.ToString(yyyyMMdd-HHmm))</VersionSuffix>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Development'">
    <VersionSuffix>beta</VersionSuffix>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Backlot.Core\Backlot.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.1.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\bl.png">
      <Pack>True</Pack>
      <PackagePath>
      </PackagePath>
      <Link>bl.png</Link>
    </None>
  </ItemGroup>
</Project>
