<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <VersionPrefix>0.0.1</VersionPrefix>
        <VersionSuffix>
        </VersionSuffix>
        <Title>Backlot.Authentication.BuiltIn.Redis</Title>
        <Authors>Jeroen Wijdeven Holding B.V.</Authors>
        <Copyright>(c) copyright Jeroen Wijdeven Holding B.V. 2026</Copyright>
        <PackageProjectUrl>https://www.backlot.software</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
        <PackageIcon>bl.png</PackageIcon>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Configurations>Debug;Release;Development</Configurations>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Backlot.Core\Backlot.Core.csproj" />
      <ProjectReference Include="..\Backlot.Authentication.BuiltIn\Backlot.Authentication.BuiltIn.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="StackExchange.Redis" Version="2.13.17" />
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <VersionSuffix>alpha-$([System.DateTime]::UtcNow.ToString(yyyyMMdd-HHmm))</VersionSuffix>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Development'">
        <VersionSuffix>beta</VersionSuffix>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\bl.png">
            <Pack>True</Pack>
            <PackagePath>
            </PackagePath>
            <Link>bl.png</Link>
        </None>
    </ItemGroup>
</Project>
